name: compound
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  firebase_storage: ^12.4.5
  cloud_firestore: ^5.6.7
  firebase_messaging: ^15.2.5
  provider: ^6.1.5
  flutter_riverpod: ^2.4.9
  intl_phone_number_input: ^0.7.3
  pin_code_fields: ^8.0.1
  fl_chart: ^0.65.0
  cached_network_image: ^3.4.1
  timeago: ^3.7.0
  flutter_local_notifications: ^19.1.0
  image_picker: ^1.1.2
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  url_launcher: ^6.3.1
  photo_view: ^0.15.0
  carousel_slider: ^5.0.0
  youtube_player_flutter: ^9.1.1
  file_picker: ^10.1.7
  path: ^1.9.1
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0



# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
