// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyjXN6qmxa8nm7elVKUnas_wlkFhGoRuM',
    appId: '1:517644308042:android:c4857429474734e670e0b3',
    messagingSenderId: '517644308042',
    projectId: 'rdbt-6ac7c',
    databaseURL: 'https://rdbt-6ac7c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rdbt-6ac7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyjXN6qmxa8nm7elVKUnas_wlkFhGoRuM',
    appId: '1:408173237432:ios:b52743e4dce06b9797504d',
    messagingSenderId: '408173237432',
    projectId: 'thepyramidscomp',
    databaseURL: 'https://thepyramidscomp.firebaseio.com',
    storageBucket: 'thepyramidscomp.appspot.com',
    iosBundleId: 'com.Pyramids.projectpyramids',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyjXN6qmxa8nm7elVKUnas_wlkFhGoRuM',
    appId: '1:517644308042:web:8e34fe7da38e957470e0b3',
    messagingSenderId: '517644308042',
    projectId: 'rdbt-6ac7c',
  );
}
